In [2]:
## Now let analyse the sentiment of the headline and assign a score for it using finbert.
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline

model_name = "ProsusAI/finbert"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(model_name)

classifier = pipeline(
    "sentiment-analysis",
    model=model,
    tokenizer=tokenizer
)

headline = "Apple reports record quarterly earnings."

result = classifier(headline)

print(result)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[{'label': 'positive', 'score': 0.9131031036376953}]

In [4]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Venky-MIT/capstone/Filtered_external.csv")
df.head()

,Unnamed: 0,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
0,6680,2020-06-10 07:33:26+00:00,Tech Stocks And FAANGS Strong Again To Start D...,AAPL,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,NaN,NaN,NaN,NaN,NaN,NaN
1,6681,2020-06-10 04:14:08+00:00,10 Biggest Price Target Changes For Wednesday,AAPL,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN
2,6682,2020-06-10 03:53:47+00:00,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",AAPL,https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
3,6683,2020-06-10 03:19:25+00:00,"Deutsche Bank Maintains Buy on Apple, Raises P...",AAPL,https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN
4,6684,2020-06-10 02:27:11+00:00,Apple To Let Users Trade In Their Mac Computer...,AAPL,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.describe()

,Unnamed: 0,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
count,7.526000e+03,0.0,0.0,0.0,0.0,0.0,0.0
mean,8.996184e+05,NaN,NaN,NaN,NaN,NaN,NaN
std,4.790110e+05,NaN,NaN,NaN,NaN,NaN,NaN
min,6.680000e+03,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.677412e+05,NaN,NaN,NaN,NaN,NaN,NaN
50%,9.257355e+05,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.255421e+06,NaN,NaN,NaN,NaN,NaN,NaN
max,2.923509e+06,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.Stock_symbol.value_counts()

Stock_symbol
NVDA     3146
TSLA     1875
GOOGL    1754
AAPL      473
AMZN      278
Name: count, dtype: int64

In [11]:
def get_sentiment(text):
    if pd.isna(text):
        return None, None
    result = classifier(text)[0]
    return result['label'], result['score']

# Apply sentiment analysis to the 'Article_title' column
df[['sentiment_label', 'sentiment_score']] = df['Article_title'].apply(lambda x: pd.Series(get_sentiment(x)))

df.to_csv("/content/drive/MyDrive/Venky-MIT/capstone/Filtered_external_sentiment.csv", index=False)
# Display the DataFrame with the new sentiment columns
display(df.head())

,Unnamed: 0,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary,sentiment_label,sentiment_score
0,6680,2020-06-10 07:33:26+00:00,Tech Stocks And FAANGS Strong Again To Start D...,AAPL,https://www.benzinga.com/government/20/06/1622...,JJ Kinahan,NaN,NaN,NaN,NaN,NaN,NaN,positive,0.865888
1,6681,2020-06-10 04:14:08+00:00,10 Biggest Price Target Changes For Wednesday,AAPL,https://www.benzinga.com/analyst-ratings/price...,Lisa Levin,NaN,NaN,NaN,NaN,NaN,NaN,neutral,0.814269
2,6682,2020-06-10 03:53:47+00:00,"Benzinga Pro's Top 5 Stocks To Watch For Wed.,...",AAPL,https://www.benzinga.com/short-sellers/20/06/1...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN,neutral,0.933910
3,6683,2020-06-10 03:19:25+00:00,"Deutsche Bank Maintains Buy on Apple, Raises P...",AAPL,https://www.benzinga.com/news/20/06/16219873/d...,Benzinga Newsdesk,NaN,NaN,NaN,NaN,NaN,NaN,positive,0.748401
4,6684,2020-06-10 02:27:11+00:00,Apple To Let Users Trade In Their Mac Computer...,AAPL,https://www.benzinga.com/news/20/06/16218697/a...,Neer Varshney,NaN,NaN,NaN,NaN,NaN,NaN,neutral,0.943328

In [ ]:
df.to_csv("/content/drive/MyDrive/Venky-MIT/capstone/Filtered_external_sentiment.csv", index=False)